#
#  ### Params for Gauss driver ###
#

#
#  Communication with motors
#

# Dynamixel bus
dxl_baudrate:         1000000
dxl_uart_device_name: "/dev/serial0"

# CAN bus
spi_channel:        0
spi_baudrate:       1000000
gpio_can_interrupt: 6

#
#  Read/Write/Check frequencies 
#  Those params have been chosen to get a good (connection performance + speed / CPU usage) ratio
#

ros_control_loop_frequency:              80.0

gauss_hw_check_connection_frequency:     2.0
publish_hw_status_frequency:             1.0
publish_software_version_frequency:      1.0
publish_learning_mode_frequency:         1.0
read_rpi_diagnostics_frequency:          0.25

dxl_hardware_control_loop_frequency:     50.0
dxl_hw_write_frequency:                  50.0
dxl_hw_data_read_frequency:              25.0
dxl_hw_status_read_frequency:            0.5

can_hardware_control_loop_frequency:     60.0
can_hw_write_frequency:                  60.0
can_hw_check_connection_frequency:       1.0

data_control_loop_frequency:             80.0
