#!/usr/bin/env python

import robot_upstart
import os

home_dir = os.getenv('HOME') 
log_dir = str(home_dir) + '/.ros/log'

j = robot_upstart.Job(name="gauss_ros", log_path=log_dir)

# other launch files will be launched in gauss_ros_setup
j.add(package="gauss_bringup", filename="launch/rpi_setup.launch")

j.install()

